name: systempao
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - altair==6.0.0
      - annotated-types==0.7.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - cryptography==46.0.3
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.47.0
      - google-auth-httplib2==0.3.0
      - google-generativeai==0.8.6
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - httplib2==0.31.0
      - idna==3.11
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - narwhals==2.15.0
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - plotly==6.5.0
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - rsa==4.9.1
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.52.2
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uritemplate==4.2.0
      - urllib3==2.6.2
      - watchdog==6.0.0
prefix: C:\Users\rossi\anaconda3\envs\systempao
